/* Generated by ps5vr/tools/gen_export_table.py - do not edit. */
static const export_sig_t klibSceHmd2Exports[] = {
  {"sceHmd2Initialize", 0x2a670},
  {"sceHmd2Terminate", 0x2a710},
  {"sceHmd2Open", 0x2a740},
  {"sceHmd2Close", 0x2a8e0},
  {"sceHmd2GetDeviceInformation", 0x2ab90},
  {"sceHmd2GetFieldOfViewWithoutHandle", 0x27940},
  {"sceHmd2ReprojectionQueryBufferSizeAlign", 0x218c0},
  {"sceHmd2ReprojectionQueryDisplayBufferSizeAlign", 0x21940},
  {"sceHmd2ReprojectionInitialize", 0x21a00},
  {"sceHmd2ReprojectionTerminate", 0x21df0},
  {"sceHmd2ReprojectionEnableVrMode", 0x21f00},
  {"sceHmd2ReprojectionDisableVrMode", 0x21f90},
  {"sceHmd2ReprojectionBeginFrame", 0x220d0},
  {"sceHmd2ReprojectionGetPredictedDisplayTime", 0x220e0},
  {"sceHmd2ReprojectionSetRenderConfig", 0x22130},
  {"sceHmd2ReprojectionGetMirroringWorkMemorySizeAlign", 0x221b0},
  {"sceHmd2ReprojectionGetMirroringDisplayBufferSizeAlign", 0x221c0},
  {"sceHmd2ReprojectionEnableMirroring", 0x221d0},
  {"sceHmd2ReprojectionDisableMirroring", 0x22250},
  {"sceHmd2ReprojectionSetMirroringOption", 0x222c0},
  {"sceHmd2ReprojectionSetParam", 0x22110},
  {"sceHmd2InternalImageOpenBySlot", 0x30120},
  {"sceHmd2InternalLedDetectorOpenBySlot", 0x2f740},
  {"sceHmd2GazeGetResult", 0x35510},
  {"sceHmd2SetVibration", 0x2ae00},
  {"sceHmd2InternalGazeStart", 0x31b60},
  {"sceHmd2InternalGazeStop", 0x31b80},
};
static const export_anchor_t klibSceHmd2Anchor = {0x7c686, "Not Initialized"};
static const export_sig_t klibSceVrTracker2Exports[] = {
  {"sceVrTracker2QueryMemory", 0xe0},
  {"sceVrTracker2Initialize", 0x230},
  {"sceVrTracker2Finalize", 0x1140},
  {"sceVrTracker2RegisterDevice", 0x11e0},
  {"sceVrTracker2UnregisterDevice", 0x13d0},
  {"sceVrTracker2GetResult", 0x2890},
};
static const export_anchor_t klibSceVrTracker2Anchor = {0x1225e5, "MININLIERS-FOR-MULTICAMSTRICTGRAVITYBOOT"};
static const export_sig_t klibSceVrHandExports[] = {
  {"sceVrHandInitialize", 0x197c0},
  {"sceVrHandFinalize", 0x1a540},
  {"sceVrHandStart", 0x1a750},
  {"sceVrHandStop", 0x1a6c0},
  {"sceVrHandGetResult", 0x1a9a0},
};
static const export_anchor_t klibSceVrHandAnchor = {0xb84e0, "handPose_%02d"};
static const export_sig_t klibSceSystemServiceExports[] = {
  {"sceShellCoreUtilExitApp", 0x10ab0},
};
static const export_anchor_t klibSceSystemServiceAnchor = {0x38d8c, "setting is disabled"};
